### ISSUE TITLE
zhimi.humidifier.ca4

### ISSUE THREAD

**Issue by KrzysztofHajdamowicz** [bieniu/ha-xiaomi-miio-humidifier#1]
Device is not autodiscovered, when I try to add it manually (IP + token) Home Assistant returns
> The device model is not known, not able to setup the device using config flow.  

In next step I'm able to enter token again (BTW, shouldn't be this field ommited as I've entered token once?) and use dropdown menu to select model. Unfortunately there are no `zhimi.humidifier.*` available ;(

**Comment by KrzysztofHajdamowicz** [comment]
I'm attaching home-assistant.log with debug enabled for this integration
[home-assistant.log](https://github.com/bieniu/ha-xiaomi-miio-humidifier/files/6061026/home-assistant.log)

**Comment by bieniu** [comment]
Please download `const.py` file once again.

**Comment by KrzysztofHajdamowicz** [comment]
New revision on `const.py` helped a lot! Now device entity is shown as Unavailable.
[home-assistant.log](https://github.com/bieniu/ha-xiaomi-miio-humidifier/files/6061080/home-assistant.log)
