### ISSUE TITLE
No 'version' key in the manifest file for custom integration 'xiaomi_miio'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'xiaomi_miio'

### ISSUE THREAD

**Issue by Golab** [bieniu/ha-xiaomi-miio-humidifier#4]
Can you please fix this error

No 'version' key in the manifest file for custom integration 'xiaomi_miio'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'xiaomi_miio'

**Comment by bieniu** [comment]
Close via https://github.com/bieniu/ha-xiaomi-miio-humidifier/commit/41a8292662152fd5732937e839eae3859767287d
